# Reference: https://docs.conan.io/en/latest/integrations/ci/travisci.html
os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
  - conan install .
  - mkdir build
  - cd build
  - cmake .. -G "Ninja"
  - cmake --build .
  - ctest -E "USER_INPUT|REQUIRES_SERVER" .