version: "3.8"
services:
    # Note: May need to "run" using --service-ports
    # TODO: I should probably figure out a neater way to include folder during build time
    #       I'm relying on mounting volumes during runtime instead of managing the Dockerfile context
    client:
        #entrypoint: ash # Interactive
        image: ristretto-client:latest
        devices:
            - "/dev/snd:/dev/snd" # Haven't tested this yet, should be able to get sound input from ALSA
        #ports:
        #    - 5050:5050
        network_mode: host
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/client_build_cache:/opt/ristretto/build
            - ../caches/client_conan_cache:/root/.conan/data
            - ../caches/client_vscode:/opt/ristretto/.vscode/
            # Exclusions:
            # This dir
            - /opt/ristretto/docker
            # server's build caches
            - /opt/ristretto/caches/server_vscode/
            - /opt/ristretto/caches/server_build_cache/
            - /opt/ristretto/caches/server_conan_cache/
        build:
            context: .
            dockerfile: ./Client.Dockerfile
    server:
        # Requires a computer with CUDA support
        #entrypoint: bash # Interactive
        image: ristretto-server:latest
        #ports:
        #    - 5051:5051
        network_mode: host
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/server_build_cache:/opt/ristretto/build
            - ../caches/server_conan_cache:/root/.conan/data
            - ../caches/server_vscode:/opt/ristretto/.vscode/
            # Exclusions:
            # This dir
            - /opt/ristretto/docker
            # client's build caches
            - /opt/ristretto/caches/client_vscode/
            - /opt/ristretto/caches/client_build_cache/
            - /opt/ristretto/caches/client_conan_cache/
        build:
           # target: grpc-build # useful if not going to run server
            context: .
            dockerfile: ./Server.Dockerfile
