version: "3.8"
services:
    server:
        image: ristretto:latest
        ports:
            - 5050:5050
        volumes:
            - ../:/opt/ristretto
            # Exclude the build and .vscode folders from being mounted
            - /opt/ristretto/build/
            - /opt/ristretto/.vscode/
        working_dir: /opt/ristretto
        entrypoint: bash
        build:
            context: .
            dockerfile: Dockerfile
            #target: buildenv