version: "3.8"
services:
    # Note: May need to "run" using --service-ports
    # TODO: I should probably figure out a neater way to include folder during build time
    #       I'm relying on mounting volumes during runtime instead of managing the Dockerfile context
    client:
        entrypoint: ash
        image: ristretto-client:latest
        devices:
            - "/dev/snd:/dev/snd" # Haven't tested this yet, should be able to get sound input from ALSA
        #ports:
        #    - 5050:5050
        network_mode: host
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/client_build_cache:/opt/ristretto/build
            - ../caches/client_conan_cache:/root/.conan/data
            # Exclusions:
            # .vscode folder
            - /opt/ristretto/.vscode/
            # server's build caches
            - /opt/ristretto/caches/server_build_cache/
            - /opt/ristretto/caches/server_conan_cache/
        working_dir: /opt/ristretto/build
        build:
            context: .
            dockerfile: ../src/client/docker/Dockerfile
    server:
        # Requires a computer with CUDA support
        entrypoint: bash
        working_dir: /opt/ristretto/build
        image: ristretto-server:latest
        #ports:
        #    - 5051:5051
        network_mode: host
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/server_build_cache:/opt/ristretto/build
            - ../caches/server_conan_cache:/root/.conan/data
            # Exclusions:
            # .vscode folder
            - /opt/ristretto/.vscode/
            # client's build cahces
            - /opt/ristretto/caches/client_build_cache/
            - /opt/ristretto/caches/client_conan_cache/
        build:
           # target: grpc-build # useful if not going to run server
            context: .
            dockerfile: ../src/server/docker/Dockerfile
