# This is a basic workflow to help you get started with Actions

name: Ristretto CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache the conan data
      uses: actions/checkout@v2
      with:
        path: |
             ./caches/client_conan_cache
             ./caches/server_conan_cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
   
    - name: Pull client image
      working-directory: ./docker
      run: docker-compose pull client
      
    - name: Compile client
      working-directory: ./docker
      run: docker-compose run client
    
#    - name: Test client
#      working-directory: ./docker
#      run: docker-compose run client
   
    - name: Pull server image
      working-directory: ./docker
      run: docker-compose pull server
    
    - name: Compile server
      working-directory: ./docker
      run: docker-compose run server
