# This is a basic workflow to help you get started with Actions

name: Ristretto CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Cache the conan data
      uses: actions/checkout@v2
      with:
        path: |
             ./caches/client_conan_cache
             ./caches/server_conan_cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
   
    - name: Build client image
      working-directory: ./docker
      run: docker-compose build client
      
    - name: Compile client
      working-directory: ./docker
      run: docker-compose run client
    
#    - name: Test client
#      working-directory: ./docker
#      run: docker-compose run client
   
    - name: Build server image
      working-directory: ./docker
      run: docker-compose build server
    
      # Runs a set of commands using the runners shell
    - name: Compile server
      working-directory: ./docker
      run: docker-compose run server
